name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: |
          go test ./...
          go test -race ./...
          go test $(go list ./... | grep -v examples) -v -coverprofile=coverage.out -covermode=atomic
          total=$(go tool cover -func=cover.out | tail -1)
          echo ${total}
          coverage=$(echo ${total} | grep -P '\d+\.\d+(?=\%)' -o)
          (( $(awk 'BEGIN {print ("'${coverage}'" >= "'30'")}') )) || (echo "单测覆盖率低于30%"; exit 1)

  # struct字段对齐
  # goleak检测 [uber-go/goleak: Goroutine leak detector](https://github.com/uber-go/goleak)
  # race test检测



#      - name: Test
#        run: go test -v -race -coverpkg=./... -coverprofile=coverage.txt ./...
#
#      - uses: codecov/codecov-action@v3

#  test-cache:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/setup-go@v3
#        with:
#          go-version: 1.20.x
#      - uses: actions/checkout@v3
#      - uses: actions/cache@v3
#        with:
#          path: |
#            ~/go/pkg/mod
#            ~/.cache/go-build
#            ~/Library/Caches/go-build
#            ~\AppData\Local\go-build
#          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
#          restore-keys: |
#            ${{ runner.os }}-go-${{ matrix.go-version }}-
#      - run: go test ./...



  CodeQL:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        # Override automatic language detection by changing the below list
        # Supported options are ['csharp', 'cpp', 'go', 'java', 'javascript', 'python']
        language: ['go']
        # Learn more...
        # https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#overriding-automatic-language-detection
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
          # If you wish to specify custom queries, you can do so here or in a config file.
          # By default, queries listed here will override any specified in a config file.
          # Prefix the list here with "+" to use these queries and those in the config file.
          # queries: ./path/to/local/query, your-org/your-repo/queries@main

      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see below)
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      # ℹ️ Command-line programs to run using the OS shell.
      # 📚 https://git.io/JvXDl

      # ✏️ If the Autobuild fails above, remove it and uncomment the following three lines
      #    and modify them (or add more) to build your code if your project
      #    uses a compiled language
      #      - run: |
      #         make bootstrap
      #         make release
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1



  CodeCOV:
    strategy:
      matrix:
        go-version:
          - 1.15.x
          - 1.16.x
          - 1.17.x
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
    runs-on: ${{ matrix.os }}
    env:
      GO_TARGET_VERSION: 1.17.x
      OS_CODE_COVERAGE: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ env.CODECOV_TOKEN != null }} && ${{ matrix.os == env.OS_CODE_COVERAGE }} && ${{ matrix.go-version == env.GO_TARGET_VERSION }}
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
          fail_ci_if_error: true
          path_to_write_report: ./codecov_report.txt
          verbose: true