version: '3.4'

services:
  # 单节点es
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}"
    environment:
      - discovery.type=single-node
    volumes:
      - /etc/localtime:/etc/localtime
      - $DOCKER_ES_DATA_PATH$/data:/usr/share/elasticsearch/data
      - ./data/plugins:/usr/share/elasticsearch/plugins
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/logs:/user/share/elasticsearch/logs
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    depends_on:
      - elasticsearch
    image: "docker.elastic.co/logstash/logstash:${ES_VERSION}"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    links:
      - elasticsearch

  kibana:
    depends_on:
      - elasticsearch
    image: "docker.elastic.co/kibana/kibana:${ES_VERSION}"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      I18N_LOCALE: zh-CN #汉化
    volumes:
      - /etc/localtime:/etc/localtime
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - 5601:5601
    links:
      - elasticsearch

  filebeat:
    depends_on:
      - elasticsearch
      - logstash
    image: "docker.elastic.co/beats/filebeat:${ES_VERSION}"
    user: root # 必须为root，否则会因为无权限而无法启动
    environment:
      - strict.perms=false
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      # 映射到容器中[作为数据源]
      - $DOCKER_ES_DATA_PATH$/filebeat/logs:/usr/share/filebeat/logs:rw
      - $DOCKER_ES_DATA_PATH$/filebeat/data:/usr/share/filebeat/data:rw
    # 将指定容器连接到当前连接，可以设置别名，避免ip方式导致的容器重启动态改变的无法连接情况
    links:
      - logstash


# elasticsearch.yml

# 集群名称
cluster.name: "docker-cluster"
network.host: 0.0.0.0
## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
##
#xpack.license.self_generated.type: trial
#xpack.security.enabled: true
xpack.security.enabled: true
xpack.license.self_generated.type: basic
#xpack.security.transport.ssl.enabled: true
# 控制洪水阶段水印。它默认为95％
#cluster.routing.allocation.disk.watermark.flood_stage: 99%
#  或者
#cluster.routing.allocation.disk.threshold_enabled: false


# kibana.yml

server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
#
elasticsearch.username: kibana_system
elasticsearch.password: ${KIBANA_SYSTEM_PASSWORD}
