version: "3.3"
services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.wrss.top'  # 容器主机名，可以用宿主机IP或域名
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.wrss.top'
        letsencrypt['enable'] = true  # GitLab 10.5 and 10.6 require this option
        letsencrypt['contact_emails'] = ['yyzw@live.com'] # 可选参数
        # gitlab_rails['gitlab_shell_ssh_port'] = 2222
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - "80:80"
      - "443:443"
      - "23:22"
    volumes:
      - ${HOME}/gitlab/data:/var/opt/gitlab
      - ${HOME}/gitlab/logs:/var/log/gitlab
      - ${HOME}/gitlab/config:/etc/gitlab
    networks:
      - gitlab
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - ${HOME}/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab

networks:
  gitlab:
    driver: bridge
