language: go
go:
  - 1.11.x
  - 1.12.x
  - master
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - tip

os:
  - linux
env:
  - GO111MODULE=on

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - make build
after_success:
  - bash <(curl -s https://codecov.io/bash)

install:
  - make build_tool

notifications:
  email:
    recipients:
      - 9a6c5609806a@gmail.com
    on_success: change
    on_failure: always
