#
# [Rules — yamllint 1.29.0 documentation](https://yamllint.readthedocs.io/en/stable/rules.html)
extends: default
yaml-files:
  - '*.yml'
  - '*.yaml'
  - '*.yamllint'
rules:
  document-start: disable
  line-length:
    max: 200
    level: warning
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 2  # 行内注释离正文最少2格
  comments-indentation: {}  # 整行注释的锁进
  brackets:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 0  # obj内不应有空格，比如[1, 2, abc]而非[ 1, 2, abc ]
    min-spaces-inside-empty: -1
    max-spaces-inside-empty: -1
#  new-line-at-end-of-file: false  # 实际上yml文件不需要留空行
  truthy:
    allowed-values: ['true', 'false', 'on']  # 自定义添加gh-ac的values
    check-keys: true
  trailing-spaces:
    level: error
